# Generated by Django 5.2.7 on 2025-10-27 20:18

import django.core.validators
import django.db.models.deletion
import dottify.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0')), dottify.models.validate_rating])),
            ],
        ),
        migrations.CreateModel(
            name='DottifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, default='no_cover.jpg', null=True, upload_to='')),
                ('title', models.CharField(max_length=800)),
                ('artist_name', models.CharField(max_length=800)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('format', models.CharField(blank=True, choices=[('SNGL', 'Single'), ('RMST', 'Remaster'), ('DLUX', 'Deluxe Edition'), ('COMP', 'Compilation'), ('LIVE', 'Live Recording')], max_length=4, null=True)),
                ('release_date', models.DateField(validators=[dottify.models.validate_release_date])),
                ('slug', models.SlugField(blank=True, editable=False, max_length=800, null=True)),
                ('artist_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dottify.dottifyuser')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('position', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='dottify.album')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Unlisted'), (2, 'Public')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dottify.dottifyuser')),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='dottify.song')),
            ],
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('title', 'artist_name', 'format'), name='unique_title_artist_format'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('album', 'title'), name='unique_album_title'),
        ),
    ]
