# Generated by Django 5.2.7 on 2025-11-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottify', '0002_alter_song_options_rename_length_song_running_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='running_time',
            new_name='length',
        ),
    ]
